name: scraper.py

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch: # Allows manual click to run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Libraries
        run: pip install -r requirements.txt
        
      - name: Run Update Script
        env:
          TG_API_ID: ${{ secrets.API_ID }}
          TG_API_HASH: ${{ secrets.API_HASH }}
          TG_SESSION: ${{ secrets.SESSION_STRING }}
        run: python update_library.py
        
      - name: Commit & Push Changes
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@noreply.com"
          git add database.csv index.html images/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update books" && git push)
